import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export const metadata = {
//   title: {
//     default: "Home | DocAppoint",
//     template: "%s | DocAppoint", 
//   },
//   description: "Book appointments with experienced doctors easily.",
// };
export const metadata = {
  title: {
    default: "Home | DocAppoint",
    template: "%s | DocAppoint", 
  },
  description: "Book appointments with experienced doctors and receive quality healthcare support anytime.",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
